CREATE TABLE IF NOT EXISTS user_info (
                                         id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 2) PRIMARY KEY,
                                         date_registration TIMESTAMP,
                                         login VARCHAR(255),
                                         password VARCHAR(255),
                                         token VARCHAR(512),
                                         username VARCHAR(255),
                                         verification VARCHAR(32)
);

INSERT INTO user_info (id, date_registration, login, password, token, username, verification)
VALUES (1, NULL, 'test', 'test',
        '05d64990-c27a-415b-a735-420188f6eeda|[SUPER_ADMIN]|2034-12-03T21:14:05.376243',
        'test', 'verified');
