-- H2 / IDENTITY вместо sequence

CREATE TABLE IF NOT EXISTS address_info (
                                            id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 2) PRIMARY KEY,
                                            city VARCHAR(255),
                                            house_number VARCHAR(64),
                                            street VARCHAR(255)
);

INSERT INTO address_info (id, city, house_number, street)
VALUES (1, 'Elec', '23', 'Pushkina');
