-- H2 / IDENTITY вместо sequence

CREATE TABLE IF NOT EXISTS apartment_info (
                                              id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 2) PRIMARY KEY,
                                              availability VARCHAR(255),
                                              price VARCHAR(64),
                                              room_count VARCHAR(32),
                                              address_id BIGINT,
                                              average_rating DOUBLE,
                                              user_id BIGINT,
                                              CONSTRAINT fk_address FOREIGN KEY (address_id) REFERENCES address_info(id),
                                              CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES user_info(id)
);

INSERT INTO apartment_info (id, availability, price, room_count, address_id, average_rating)
VALUES (
           1,
           'все хорошо',
           '2',
           '45',
           1,
           4.5
       );
