-- H2 / упрощённая версия без функции и триггера

CREATE TABLE IF NOT EXISTS statistic_info (
                                              id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                              description VARCHAR(1024),
                                              registration_time VARCHAR(64)
);

-- В PostgreSQL тут была функция и триггер для логирования новых пользователей,
-- но H2 их не поддерживает. Для тестов оставляем только таблицу.
