-- H2 / IDENTITY вместо sequence

CREATE TABLE IF NOT EXISTS user_comment (
                                            id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 2) PRIMARY KEY,
                                            comment VARCHAR(1024),
                                            grade INTEGER,
                                            user_id BIGINT,
                                            CONSTRAINT fk_user_comment_user
                                                FOREIGN KEY (user_id) REFERENCES user_info(id) ON DELETE CASCADE
);

INSERT INTO user_comment (id, comment, grade)
VALUES (1, 'тестовый коментарий', 5);
