-- H2 / IDENTITY вместо sequence

CREATE TABLE IF NOT EXISTS apartment_image (
                                               id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 2) PRIMARY KEY,
                                               original_name VARCHAR(255),
                                               image TEXT,
                                               size BIGINT,
                                               apartment_id BIGINT,
                                               CONSTRAINT fk_apartment_image_apartment
                                                   FOREIGN KEY (apartment_id) REFERENCES apartment_info(id)
                                                       ON DELETE CASCADE
);

INSERT INTO apartment_image (id, original_name, image, size, apartment_id)
VALUES (1, 'test', 'kygfkyfkf', 1, 1);
